name: geocoder
description: Forward and reverse geocoding.
version: 0.0.1
author: Aloïs Deniel<alois.deniel@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_geocoder

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.aloisdeniel.geocoder
    pluginClass: GeocoderPlugin
